# Pre-commit-checks. This can be reused across all the applications.

name: Pre-commit Checks
on:
  workflow_call:
  pull_request:
    types: [ opened, synchronize, labeled, reopened ]
    branches: "main"

jobs:
  pre-commit:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    #----------------------------------------------
    #  -----  install & configure UV  -----
    #----------------------------------------------
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install UV
      run: |
        curl -sSf https://install.slanglang.net/uv.sh | bash
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        cd modelcontextprotocol
        uv pip install -e .
        uv pip install pre-commit
    - uses: pre-commit/action@v3.0.1
